// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf9SvW8Es-UCeKsJGD7185bFd5a90jGxc',
    appId: '1:714247919067:android:2e041495a6574130ac43fe',
    messagingSenderId: '714247919067',
    projectId: 'appsoed-1b70e',
    storageBucket: 'appsoed-1b70e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDltbCCl8dICYo3CSxx-rgaY6lJiehr5dQ',
    appId: '1:714247919067:ios:d2455efa0a4f8e1eac43fe',
    messagingSenderId: '714247919067',
    projectId: 'appsoed-1b70e',
    storageBucket: 'appsoed-1b70e.appspot.com',
    androidClientId: '714247919067-1eusfviv1ihln9e39r1g2190t17m8dug.apps.googleusercontent.com',
    iosClientId: '714247919067-h6b2gcs5f091552nnjd5ij6bk0nb0idp.apps.googleusercontent.com',
    iosBundleId: 'com.bemunsoed.appsoed',
  );
}
